### ISSUE TITLE
Keynote file can't be opened

### ISSUE THREAD

**Issue by jakebromberg** [robrix/Postmodern-Programming#4]
I get the same error in Keynote '14 and '09. Other Keynote files on my machine open correctly.

**Comment by robrix** [comment]
What error is that…? It opens fine here.

**Comment by jakebromberg** [comment]
Hmm don't get any specific error.

![screen shot 2015-05-25 at 9 46 46 am](https://cloud.githubusercontent.com/assets/445782/7799977/12ed5562-02c3-11e5-9e57-b312ad44fffa.png)

**Comment by jakebromberg** [comment]
This happens on both my home and work laptops.

**Comment by robrix** [comment]
Is anything logged to the console?

**Comment by jakebromberg** [comment]
Haha, I looked at the console output and it's an importing issue. Works fine when I open with Keynote '09.

**Comment by jakebromberg** [comment]
For reference:

```
5/25/15 2:29:57.092 PM Keynote[15658]: *** Assertion failure #2: -[TSAImportController prepareForImportDisplayingProgress:] TSAImportController.m:295 Could not create importer for document at /Users/jake/Downloads/Postmodern Programming.key.
```

**Comment by robrix** [comment]
Thanks for posting that! I don’t think there’s anything for me to do about this, so I’m going to close the issue out.
